name: Deploy Streamlit App

on:
  push:
    branches:
      - main  # Adjust this if you use another branch for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "API_KEY=${{ secrets.API_KEY }}" > .env

      - name: Run Streamlit App
        run: streamlit run streamlit_app.py
